# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   bridgecrew:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:
       api-key: ${{ secrets.BRIDGECREW_API_KEY }}
       directory: "terragoat-1/terraform"
       soft_fail: false
       framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
       output_format: cli
       quiet: false
       external_checks_dir: ./checkov
       download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
       log_level: DEBUG # optional: set log level. Default WARNING
